try:
    while True:
        continue
except:
    print('exception handled')